### ISSUE TITLE
The Lighting Bug [1.14]

### ISSUE THREAD

**Issue by Awesomespore** [VazkiiMods/Botania#3140] opened 2020-01-13 20:38 UTC
So, since the mod was updated to 1.14, there has been a bug where if I unload certain chunks and reload them again, those chunks become completely dark, and light sources don't emit light.

After some time, I'm getting really suspicious of the mana spreader, as this lighting bug only ever seems to affect chunks that have mana spreaders placed in them. Here's an image.
![2020-01-14_09 29 53](https://user-images.githubusercontent.com/59407684/72290129-68961900-36b1-11ea-9868-a227a3c56a6d.png) (Notice how the chunk that has a pure daisy in it is normal, hence why I suspect it's the spreaders, not the flowers.)

**Comment by Awesomespore** [comment] 2020-01-13 20:59
Hmm... after thorough testing in a test world, I have come to the conclusion that I honestly don't know.
This is the strangest issue I've ever seen. In a chunk with just Endoflames, they vanish and the chunk goes dark
In a chunk with just Endoflames and torches, they all vanish.
In a chunk with mana pools, spreaders, petal apothecaries, endoflames and torches, the chunk goes dark and the torches and endoflames vanish.
In a chunk with all of the above as well as light emitting blocks such as glowstone and jack o lanterns, the chunk goes dark, but those vanish as well as the endoflames, but the torches don't vanish.
Replacing the endoflames with another generating flora such as a thermalily, only the thermalily vanishes, but the chunk does not go dark.
Same story with functional flora.
This is very strange.......

**Comment by williewillus** [comment] 2020-01-14 00:45
i doubt this is a botania specific bug
vanilla 1.14 is buggy
forge seems to make it even worse

**Comment by williewillus** [comment] 2020-01-14 00:45
additionally, botania doesn't mess with chunk lighting at all, in that regard it's a pretty normal mod.

can you get it to happen on just plain forge?

**Comment by EStuffs** [comment] 2020-01-18 23:13
Yeah, I'm having the same issue

**Comment by Orncaex** [comment] 2020-01-19 13:19
Can confirm that my Endoflame setup with the basic spreader and mana pool is causing a dark spot... didnt happen till i went to go to the neither. then just now when i went to chase burried treasure.
![Dark chunk](https://user-images.githubusercontent.com/39629424/72681691-ac12cd80-3a8b-11ea-9bec-58437593e30f.png)

the only major mods are mostly UI stuff... JEI, more Overlays.... whatever this is might be somewhere between those three botania items

**Comment by Silbersurfer01** [comment] 2020-01-22 15:31
the problem with the light bug, i could find in the preference of botania under the position [shaders]
enabled from true to false
remedy.
hope it works for you too.

**Comment by LezChap** [comment] 2020-01-22 19:06
I have this bug as well...only started seeing it after Botania was added to the modpack's instance.  Not all chunks impacted have a mana spreader though, but all chunks DO have a functional flower (some floating, some not).  As far as I can tell, Botania is the only thing that connects everything.
Examples: 
https://imgur.com/KLrGo5i
From left to right, the far left chunk has a Solegnolia (planted)...  The middle chunk has a Solegnolia (floating iirc) and some spreaders and manapools, a couple with sparks.  The right chunk has a Solegnolia and a Jaded Amaranthus ( both floating),  and various mystical flowers from the JA.
https://imgur.com/bVd70ar
Left Chunk has Pure Daisies (planted) and I believe a Hoppercock(floating) is in that chunk underground.  The furthest chunk has a floating hoppercock, the front center chunk has several Shulk-Me-Nots and a Heisei Dream (all Floating) as well as some Endoflames (both visible in the SS and underground, all planted).  The right chunk has more of those Endoflames (planted) and a Hoppercock (floating).

I have manapools and spreaders in unaffected chunks, but every chunk impacted seems to have a functional flower of some variety in it.  I don't know if this helps track it down.

**Comment by williewillus** [comment] 2020-01-22 21:26
This might be related to https://github.com/MinecraftForge/MinecraftForge/pull/6433, but that PR has only been merged into 1.15

**Comment by tiggerbiggo** [comment] 2020-01-23 00:08
This is happening to me without mana pools, and is happening with hopperhocks, both floating and normal. In addition, I set up an hourglass next to a vanilla redstone lamp to try and trigger an update every so often, and the lamps got stuck when the darkness triggered again. Something seriously weird here, since it only happens sometimes and I have gone a whole game of many hours without encountering it, then suddenly encountered it in 4 chunks in rapid succession...

**Comment by williewillus** [comment] 2020-01-23 00:18
so the chunk stopped ticking when the lighting issue happened? we saw that happen on the patron server as well, it seemed to be tile entities in general being weird.

**Comment by tiggerbiggo** [comment] 2020-01-23 01:35
Well the hourglass was still turning but the lamp was "on" all the time and
it was dark completely.

**Comment by williewillus** [comment] 2020-01-23 19:21
Yes, that's what we saw as well.
Can you build and test master after resetting the state and relighting everything? (Or on a fresh world)

**Comment by Awesomespore** [comment] 2020-01-26 07:32
In the more recent updates for Botania, I haven't seen this issue occur so far, so that's promising!

**Comment by carmelroro** [comment] 2020-01-26 15:10
I am experiencing it on r1.11-376 on our server. I had placed and endoflame, a manapool, diluted manapool, and 3 manaspreders in a chunk together and got this glitch. After finding this thread I broke down the spreaders and left the endoflame. It seemed to fix it until I Tried to capitalize on the glitch by making a mob farm. I moved the spreaders to another chunk to start that and when I put them back down the glitch happened back in the original chunk.

**Comment by khandnalie** [comment] 2020-02-04 03:36
I am experiencing this on my server. Botania+r1.11-376 with forge-1.14.4-28.2.0, (though I experienced it likewise with forge 28.1.115/117). I can confirm that it does seem to happen to chunks with Botania flowers in them. I have also noticed that this issue seems to occur more often in chunks with more entities in them. This issue seems to be related/identical to MC-142134, which affected 1.14.0 through 1.14.2. Both affected chunks also contained mana spreaders. A previous world encountered this same issue (I didn't get screenshots) in a chunk which had no spreaders, but did have sparks. This was also accompanied by severe lag spikes which came up every time the chunk was loaded. 
![2020-02-03_22 31 55](https://user-images.githubusercontent.com/60636229/73711554-3cc8ea80-46d5-11ea-91a6-3b6590e408c7.png)

**Comment by carmelroro** [comment] 2020-02-09 16:04
Updated the server to r1.11-377 at first it looked like it was fixed. So far there haven't been any "Blackhole" effects of just no visible light, but the actual light level seems to hit or miss. When I first updated it seemed like it was working. Placed a torch and light level went up. But after playing for a while mobs started to spawn in the chunk and the light level went back to 0. Placing another torch raised it back up for a little while then it went back down.

**Comment by williewillus** [comment] 2020-02-09 21:49
yeah I don't know anymore then. there's nearly zero custom light level code left in botania after 377 (only apothecaries and alf portals)

it's probably a vanilla/forge chunkloading issue

**Comment by SkyKingTv** [comment] 2020-02-14 07:59
Hey I'm definitely having this lighting issue! Only happening with Botania installed~!

**Comment by khandnalie** [comment] 2020-02-21 23:10
I updated my server to 377, and after the update I still had the lighting issue, but only with certain chunks, namely chunks that had had the lighting issue before. As before, they would be fine after regenerating the chunk, unless the chunk got unloaded then reloaded, after which it would go back to being dark. Interestingly though, on unaffected chunks , moving out of range then coming back would simply delete all the botania blocks/entities. I would place down a few endoflames shooting mana into a pool, and when I came back they would be missing. 

Furthermore, I was unable to recreate the bug with a fresh server. I created a new server with just botania, its dependencies, and worldedit, and I was unable to recreate the lighting glitch despite moving in and out of range several times. 

Both of these tests were done with botania 377 and forge 1.14.4 - 28.2.1.

**Comment by khandnalie** [comment] 2020-02-22 02:15
I updated my server to 377, and after the update I still had the lighting issue, but only with certain chunks, namely chunks that had had the lighting issue before. As before, they would be fine after regenerating the chunk, unless the chunk got unloaded then reloaded, after which it would go back to being dark. Interestingly though, on unaffected chunks , moving out of range then coming back would simply delete all the botania blocks/entities. I would place down a few endoflames shooting mana into a pool, and when I came back they would be missing. 

Furthermore, I was unable to recreate the bug with a fresh server. I created a new server with just botania, its dependencies, and worldedit, and I was unable to recreate the lighting glitch despite moving in and out of range several times. 

Both of these tests were done with botania 377 and forge 1.14.4 - 28.2.1.

**Comment by williewillus** [comment] 2020-02-22 05:05
yes, I was able to get a 100% reproduction for this. I think botania is triggering a vanilla bug
Unfortunately, the vanilla code here is absolute spaghetti so I'm just going to put some bandaids on it and pray

**Comment by williewillus** [comment] 2020-02-22 16:16
For people that are curious, the bug seems to be when the following happens:
1. the chunk has changed and needs saving
2. you inadvertently reload the chunk after it's unloaded and while it's saving

this probably leads to a race/logic race in the logic where stuff is overwritten with bad values. This can probably manifest also as stuff vanishing or TE's becoming cursed (as we observed on the first patron world).
In this specific case I just fixed, all special flowers touched world.getblockstate in their save method, leading to the above situation. Bandaided by using the chunk-cached state, but that's not perfect since it could be the case that it unloads without ever being cached in the first place.

Will continue looking later today and next week, appreciate the patience on this.

**Comment by williewillus** [comment] 2020-02-24 06:35
please try the latest botania release (378), relight your chunks completely (preferably, use the optimize world + remove cached data option on the client, making backups), then try to reproduce this issue as much as you can

**Comment by williewillus** [comment] 2020-04-08 00:25
anyone gotten this since 378?

**Comment by carmelroro** [comment] 2020-04-08 02:45
Mine seems to be fixed

**Comment by Vaelzan** [comment] 2020-04-10 01:29
There are still issues on our server with 378. Attached is a screenshot that the impacted player sent me. The blocks in this chunk were all placed after the update to 378 (the chunk was not broken prior to this version, and did not have any blocks placed in it until then). We haven't been able to test with 379 yet, but I didn't see any changes related to this bug mentioned in the changelog, so hopefully this is still useful. These are the only Botania blocks in the chunk. He stated "the mana mirror is linked to the rightmost mana pool", if that helps. 

The only other blocks in the chunk are soulfire from Druidcraft (which is just lighting) and otherwise natural world generation and basic building blocks (ie. not tile entities or anything fancy). There are no other entities in the chunk.

![botaniachunk](https://user-images.githubusercontent.com/6418846/78953846-77a82e00-7b1d-11ea-8b08-5e435631ac4a.png)

I'm hoping that this can be fixed, although seeing in the changelog that 379 was the final 1.14.x build is a bit concerning given that this bug still appears to linger, so I am very much hoping that another bugfix build will turn up at some point if you happen to be able to resolve the issue.

I can try to get more information from the player if needed.

**Comment by Vaelzan** [comment] 2020-04-10 04:06
This is another chunk being impacted. What is visible there is basically everything that was added to the chunk (the rest is just natural terrain). I've applied the night vision effect to make the screenshot clearer - in reality it's completely dark. Again, release 378 of Botania, but different setup to the previous chunk. 

![botania-2](https://user-images.githubusercontent.com/6418846/78961187-fa3be800-7b33-11ea-86c7-e96c09ff3022.png)

**Comment by beringtom** [comment] 2020-12-23 05:24
Would like to confirm this issue is still very much present in V. 1.16.4-410
Currently got two chunks going dark but only for around 20blocks vertical.

One of the chunks only have a single Rosa Arcana in it and was effected.

**Comment by Asgatoril** [comment] 2021-01-19 18:35
Can confirm on V. 1.16.4-410. Using the Valhelsia 3 3.1.5 Modpack.

This isn't just a client side error. Mobs spawn in the dark chunks and won't burn while the sun is out. 
It looks like the chunk is flagged as being underground or something like that.

![botania_bug](https://user-images.githubusercontent.com/1699227/105077899-797c2600-5a8d-11eb-8ca5-57d08a267af8.png)

**Comment by kosma** [comment] 2021-02-18 21:33
Relating to #3669, a question: would it be possible to completely avoid calling `getBlock()` in `TileEntitySpecialFlower.write()` (and other tile entities as well)? I'm looking at the vanilla code and none of the tile entities call `getBlock()`, and I have a faint feeling it might just be not supported in that context - with the Not Supported reading its ugly head after 1.14 changed chunkloading.

**Comment by williewillus** [comment] 2021-02-18 22:59
We can probably just tell the flower when we construct it whether it's floating or not. I'll give that a shot.

**Comment by Hubry** [comment] 2021-02-21 17:58
Let's see if 081ace8c6e2f388a0884ff958cf49012709f24ca improves anything.

**Comment by Hubry** [comment] 2021-11-20 15:06
Well, that's 9 months with no responses, so I assume it did.

**Closed by Hubry** 2021-11-20 15:06 UTC
Labels: bug, confirmed

**Comment by Pultex** [comment] 2023-02-21 19:44
Sorry but on
Botania-1.19.2-437-FORGE
![2023-02-21_13 41 36](https://user-images.githubusercontent.com/34325251/220442962-f684df13-96e0-440b-bd2d-63a0a2f31cd1.png)

with forge-43.2.3
