### ISSUE TITLE
Trinket Integration NEI crash

### ISSUE THREAD

**Issue by profjb58** [VazkiiMods/Botania#3874] opened 2021-12-06 23:04 UTC
### Mod loader

Fabric

### Minecraft version

1.18

### Botania version

1.18-424

### Modloader version

Fabric Loader 0.12.8, Fabric API 0.44.0+18

### Modpack info

All of Fabric 5

### The latest.log file

https://gist.github.com/profjb58/9086d04bf4cd5eb2a61c33f45f320e29

### Issue description

Crash whilst hovering over the lava pendant whilst using Not Enough Items.
Seems to be an issue with Trinkets integration. An optional value is equating to `null`.

Only thing I could think of is maybe this item is assigned additional NBT data once it's crafted / made and that data is just blank when displayed in NEI

### Steps to reproduce

1. Hover over the Lava Pendant in NEI
2. Crash...

**Comment by Hubry** [comment] 2021-12-06 23:44
Cannot reproduce with base AoF5. The renderer is very simple and doesn't read any data from the item, and the NPE is on the model of the worn pendant, from being rendered on an another player.

Do you have the *full* game log? 
Also, I saw mentions of Dashloader from you on the AOF discord. Are you sure it isn't a fault of Dashloader?

**Comment by profjb58** [comment] 2021-12-07 03:08
Good point, apologies I forgot about dashloader. I'll re-try with and without to see what happens.

**Comment by Hubry** [comment] 2021-12-17 01:11
Closing as it is caused by a conflict with Dashloader and afaik they are fixing it on their side.

**Closed by Hubry** 2021-12-17 01:11 UTC
Labels: cant-reproduce
