### ISSUE TITLE
Ring of Loki only places up to a stack of blocks

### ISSUE THREAD

**Issue by JohnJDrake** [VazkiiMods/Botania#3668] opened 2021-02-18 11:54 UTC
# Version Information
Forge version:  36.0.14
Botania version:  1.16.4-411

# Further Information
When using the Ring of Loki to place more than 64 blocks, it only places the first stack of blocks.
When testing in creative, it does not seem to have the same issue.

**Comment by Hubry** [comment] 2021-03-05 21:41
You can use the black hole talisman to bypass this limitation, but we'll look into some fix.

**Comment by williewillus** [comment] 2021-03-06 03:59
Semi-intended

**Comment by waffleattack** [comment] 2021-03-15 16:04
> You can use the black hole talisman to bypass this limitation, but we'll look into some fix.

if you are doing it for the advancement, using the dirt wand also works i found.

**Comment by Aegide** [comment] 2023-01-06 22:34
This limit is not explained in the Lexicon, it's an unexpected behavior for a regular player.

Therefore this issue could be fixed by updating the entry to explain this limit.

**Closed** 2023-09-26 16:31 UTC
Labels: bug, minor, confirmed
