### ISSUE TITLE
Pure daisy don't have particles

### ISSUE THREAD

**Issue by GsK380** [VazkiiMods/Botania#3880] opened 2021-12-16 16:40 UTC
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18-425-FABRIC

### Modloader version

Fabric Loader 0.12.11 + API 0.44.0

### The latest.log file

No need

### Issue description

ATTENTION: Perhaps other flowers have the same problem

Pure daisy does not have particles when he is transforming wood or stone and don't have particles nearby like mystic flowers

### Steps to reproduce

1. Create new world or sign in to already created world
2. Create or pick up from the creative tab the Pure Daisy
3. Now, plant the pure daisy into the ground
4. Put the wood or stone nearby pure daisy
5. See, he is not having particles nearby a flowers and blocks when flower transforming them

**Comment by Hubry** [comment] 2021-12-16 17:36
Duplicate of https://github.com/VazkiiMods/Botania/issues/3879, wait for next build

**Closed** 2021-12-16 17:40 UTC
