### ISSUE TITLE
No Flugel Tiara boost cooldown when wearing Mekanism Mekasuit with gravitational modulating unit

### ISSUE THREAD

**Issue by T3line** [VazkiiMods/Botania#3629] opened 2021-01-29 15:59 UTC
Forge version:  Forge-35.1.36
Botania version:  Botania-1.16.4-410

Steps to reproduce:
1. Equip Mekasuit chest piece and add gravitational modulating unit via the modification station.
2. Equip a Flugel Tiara (Mana is optional since this works with and without mana).
3. Start flying around and hold Ctrl.
4. Once you boost a single time after the cooldown goes down, the cooldown will basically disappear and you'll start permanently boosting causing you to go extremely fast. If the chunks don't load fast enough you can sometimes phase through blocks and end up in a mountain.

What I expected to happen: Expected the Flugel to boost me like it's meant to with a cooldown.

What happened instead: The Flugel started boosting without cooldown into extreme speeds.

https://imgur.com/a/radqKcM

**Comment by anoomolu** [comment] 2023-11-23 00:52
I'm unable to reproduce the lack of tiara cooldown on 1.19.2. Not too familiar with Mekanism however, is tiara boosting without mana supposed to be one of the Mekasuit's features?

**Comment by anoomolu** [comment] 2023-11-23 10:39
Closing this as I was unable to reproduce this on the latest Mekanism + Botania releases for both 1.16.5 and 1.19.2.

I'm not sure if the Mekasuit allowing Tiara boosts without a mana source is intended or not, will ask on their Discord.

**Closed** 2023-11-23 10:40 UTC
Labels: investigate
