### ISSUE TITLE
Inconsistency with configuring rannuncarpus with wand of the forest

### ISSUE THREAD

**Issue by artemisSystem** [VazkiiMods/Botania#3784] opened 2021-07-29 18:30 UTC
The way of configuring rannuncarpus using a wand of the forest is inconsistent with how you would configure e.g. a hopperhock.

# Version Information
Forge version:  36.1.12
Botania version:  1.16.5-419

# Further Information
What happens:
- Rannuncarpus changes between ignore/respect block data mode when it is right clicked using a wand of the forest, regardless of bind/function mode.
- The text describing the rannuncarpus setting is white.

What i expected to happen (how hopperhock works):
- Expected the rannuncarpus to only change between ignore/respect block data mode when it is **sneak** right clicked using a wand of the forest **in function mode**.
- Expected the text describing the rannuncarpus setting to be pink/peach/whatever the color of the mana meter is, instead of white.

**Comment by williewillus** [comment] 2021-07-29 23:36
1. I looked at this before and couldn't reproduce
2. The color of the flower was too hard to read with the monocle background. Not sure how I want to handle it. Might make all tooltips for all flowers the same consistent white or gray color.

**Comment by artemisSystem** [comment] 2021-07-29 23:55
Huh, weird. guess i could investigate more tomorrow. for reference i had the rannun on top of a red string spoofer, bound to a (i think poppy) flower pot on top of farmland, and connected to a guilty pool

**Comment by Hubry** [comment] 2021-08-30 23:31
The first part is actually a duplicate of #3778, it seems - it was already fixed, next build will have it.

The only flower having some sort of configuration is the hopperhock, which has gray text. I guess I'll change to gray then.

**Closed** 2023-05-11 06:54 UTC
Labels: investigate
