### ISSUE TITLE
Hopperhock doesn't pickup witherstar

### ISSUE THREAD

**Issue by MakerTim** [VazkiiMods/Botania#2018] opened 2016-11-05 16:03 UTC
The hopperhock doesn't pick up the wither star, after its dropped from the wither
it does pick it up after i drop it

so it seemed a bit weird, so i report it 😕 

Forge 2121
Botania r1.9-337
java 1.8
Linux server, Windows client

**Comment by yrsegal** [comment] 2016-11-05 16:04
what other mods are present?

**Comment by jomin398** [comment] 2016-11-05 16:29
### Wither farm is nearby
## Collectible range of Hopperhock flower ??

**Comment by MakerTim** [comment] 2016-11-05 17:24
@yrsegal 
1.10.2/                                            ExtraBitManipulation-1.10.2-2.1.0.jar         Ping-1.10.X-1.2.2.B7-universal.jar
3DManeuverGear-1.10.2-0.10.jar                     extrautils2-1.10.2-alpha-1.2.1.jar            PSIonicUpgrades-r1.15.jar
AppleCore-mc1.10.2-2.0.1.jar                       ExtremeReactors-1.10.2-0.4.5.18.jar           Psi-r1.0-41.jar
AppleSkin-mc1.10.2-1.0.3.jar                       FastLeafDecay-v11.jar                         Quark-r1.0-57.jar
AutoRegLib-1.0-2.jar                               forestry_1.10.2-5.2.16.314.jar                Railcraft_1.10.2-10.0.0.jar
Baubles-1.10.2-1.3.2.jar                           gendustry-1.6.4.24-mc1.10.2.jar               ReAuth-3.2.jar
bdlib-1.12.2.17-mc1.10.2.jar                       Graves-1.10.2-b28-universal.jar               RecStat-1.10.2-2.2.2.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar     Guide-API-1.10.2-2.0.2-45.jar                 refinedstorage-1.2.jar
BlockDrops-1.10.2-1.0.10.jar                       ic2/                                          ResourceLoader-MC1.9.4-1.5.1.jar
BlockRenderer-1.0.0.jar                            ImmersiveEngineering-0.10-48.jar              rftools-1.10-5.58.jar
BloodArsenal-1.10.2-2.0.1-14.jar                   industrialcraft-2-2.6.87-ex110.jar            rftoolsctrl-1.10-1.5.0.jar
BloodMagic-1.9.4-2.1.0-66.jar                      IndustrialWires-1.1-3.jar                     rftoolsdim-1.10-4.44.jar
'Botania r1.9-337.jar'                             InGameAccountSwitcher-Forge-6.1.2.jar         RiceCraftingTableBeta2.jar
BrandonsCore-1.10.2-2.1.1.61-universal.jar         InventoryTweaks-1.62-dev-66.jar               roots-1.10.2-0.203.0.jar
Chameleon-1.10-2.1.7.jar                           ironchest-1.10.2-7.0.11.797.jar               RTG-1.10.2-4.1.1.4.jar
Chiseled-Me-1.0.jar.bc                             itemscroller-1.10.2-0.7.0.jar                 sampler-1.66.jar
Chisel-MC1.10.2-0.0.7.3.jar                        jei_1.10.2-3.13.2.354.jar                     Signals-1.10.2-0.4.3-universal.jar
chiselsandbits-12.7.jar                            jeibees-0.9.0.4-mc1.10.2.jar                  simpleretrogen-1.10-4.0.1+8.jar
ChiselsBytes-1.9.4-0.4.jar                         JustEnoughResources-1.10.2-0.5.4.67.jar       SpiceOfLife-mc1.9.4-1.3.6.jar
ClayBucket-1.9.4-1.1.jar                           k4lib-1.10-1.0.58-universal.jar               StorageDrawers-1.10.2-3.4.1.jar
CodeChickenCore-1.10.2-2.3.5.91-universal.jar      'LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar'  SuperCircuitMaker-1.0.1.jar
CodeChickenLib-1.10.2-2.4.3.124-universal.jar      Login_Shield-1.10.2-14-g4618728.jar           supercraftingframe-1.10.2-1.2.1.87.jar
CompactSolars-1.10.2-5.0.4.328-universal.jar       Mantle-1.10.2-1.1.1.jar                       taiga-1.10.2-1.1.4.jar
CompassCoords-1.10.2-3.1.7.jar                     mcjtylib-1.10-2.2.0.jar                       TConstruct-1.10.2-2.5.6b.jar
ComputerCraft1.80pr0.jar                           MKTPackMod-mc1.10.2.jar                       theoneprobe-1.10-1.2.1.jar
CraftingTweaks_1.10.2-6.1.16.jar                   MmmMmmMmmMmm-1.11.jar                         'Tinkers'\'' Addons-1.10.x-1.0.3.jar'
CustomMainMenu-MC1.10.2-2.0.2.jar                  modnametooltip_1.10.2-1.6.0.jar               topaddons-1.10.2-0.8.0.jar
deepresonance-1.10-1.2.8.jar                       morebees-1.10.2-1.1.4.jar                     Translocators-1.10.2-2.1.3.34-universal.jar
DefaultOptions_1.10.2-6.1.5.jar                    Morpheus-1.10.2-3.1.9.jar                     UniDict-1.10.2-1.5.jar
Draconic-Evolution-1.10.2-2.0.2.134-universal.jar  Morph-o-Tool-1.0-12.jar                       valkyrielib-1.10.2-0.10.5d.jar
ElecCore-1.9.4-1.5.303.jar                         notenoughwands-1.9.4-1.3.5.jar                Waila-1.7.0-B3_1.9.4.jar
EnderCore-1.10.2-0.4.1.58-beta.jar                 OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar       WailaHarvestability-mc1.10.2-1.1.9.jar
EnderIO-1.10.2-3.0.1.125_beta.jar                  OpenPrinter-1.9.4-0.1.0.3.jar                 zerocore-1.10.2-0.0.8.0.jar
EnderStorage-1.10.2-2.1.5.84-universal.jar         PackingTape-1.10.2-0.6.0.jar
environmentaltech-1.10.2-0.10.5g.jar               'Pam'\''s HarvestCraft 1.9.4-1.10.2h.jar'


in short, a lot

**Comment by MakerTim** [comment] 2016-11-05 17:27
@jomin398 it is getting the item when i drop it AND its collecting the shader thingy of Immersive Engeneering, thats dropped at the EXACT same spot
so on that note, i will assume that it is the hopperhock and not my setup

**Comment by yrsegal** [comment] 2016-11-05 19:00
It might be that the item for the nether star is getting replaced by a custom entity.

**Comment by MakerTim** [comment] 2016-11-05 21:03
As far for my debugging skills go,
http://i.imgur.com/TdRBGlD.png
it seems a item.item
just like every other in minecraft thats dropped, i guess its nbt that makes it explosion proof and all
not sure, im no expert on this

**Comment by yrsegal** [comment] 2016-11-05 21:04
hover over the name component for the netherstar, it gives you the entity id.

**Comment by MakerTim** [comment] 2016-11-05 21:09
http://i.imgur.com/3lfkwRW.png
Type: Item (1)

I did also a /entitydata @[r=10,type=!Player] {}
http://pastebin.com/tHkvuPWq
but i see nothing that makes it different for me

**Comment by Tamaized** [comment] 2016-11-05 21:14
That's just the UUID of the entity for the World isn't it. I don't think you'll be able to figure out if some mod is changing the EntityItem class of the Nether star item this easily. Even if they did change it they would have to extend the class for it to be even dropped in world no? I'm assuming there's some event being called and cancelled by another mod for some reason but i'm not entirely sure and I can't look into it myself right now. Hell I don't even know if there even is an event being fired this is just my guess on the whole thing.

**Comment by yrsegal** [comment] 2016-11-05 21:15
we just did tell if it's an EntityItem, which it is. Bleh.

**Comment by MakerTim** [comment] 2016-11-05 21:16
The Vacuum Chest, of enderio, is working with the entity
so there for, it should be possible somehow i figure

**Comment by Tamaized** [comment] 2016-11-05 21:17
I looked over Botania's code it just checks for nearby EntityItems so it should be working, no idea why it isn't.

**Comment by MakerTim** [comment] 2016-11-05 21:27
https://github.com/SleepyTrousers/EnderIO/blob/11e874b89e05008dfd7cf2c25566da4efa1215ff/src/main/java/crazypants/enderio/machine/vacuum/TileVacuumChest.java#L89
Looked at EnderIO, where it does pickup the item
and there they check on EntityItem class

**Comment by MakerTim** [comment] 2016-11-05 22:20
I can be blind, but doesnt they both use the same method?
https://github.com/Vazkii/Botania/blob/e38556d265fcf43273c99ea1299a35400bf0c405/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java#L69

**Comment by MakerTim** [comment] 2016-11-06 15:59
Okay, the diffrence is
getEntitiesWithinAABB - botania
vs
selectEntitiesWithinAABB - enderio

so somewhere is there a difference between them

**Comment by Tamaized** [comment] 2016-11-06 16:17
Shouldn't matter

**Comment by yrsegal** [comment] 2016-11-06 16:19
Wrong version of enderio, it's the same function. https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/machine/vacuum/TileVacuumChest.java#L101

**Comment by williewillus** [comment] 2016-11-06 16:22
Can you reproduce with just botania

**Comment by MakerTim** [comment] 2016-11-06 18:04
https://puu.sh/s8Ace.mp4
The one on the left is from a wither, right dropped

still works on my test bench where i got only Baubles (1.3.2) and Botania (337) *and ofc Forge (2121)

**Comment by unascribed** [comment] 2016-11-06 18:50
The Wither drops an EntityItem with a -6000 age, which seems to be caught by [this](https://github.com/Vazkii/Botania/blob/e38556d265fcf43273c99ea1299a35400bf0c405/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java#L80) - `age < 60 + slowdown` will always be true.

**Comment by SleepyEmber** [comment] 2021-07-15 13:52
This is still an issue in the latest version of Botania.

**Comment by williewillus** [comment] 2021-07-15 16:25
Correct. Can't really be fixed until #3507 is done, which will have to wait til 1.17 since it affects world compatibility.

**Comment by Hubry** [comment] 2021-11-20 15:05
Fixed by https://github.com/VazkiiMods/Botania/commit/b7d88a5f6edbfc26014e6ce0b2d74d6e9e60cbfc, coming in 1.17. 

Only took 5 years! 🎉

**Closed by Hubry** 2021-11-20 15:05 UTC
Labels: confirmed
