### ISSUE TITLE
Floral Obedience Stick not binding flowers via dispenser

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [VazkiiMods/Botania#3821] opened 2021-09-20 03:04 UTC
### Version info
Minecraft version: 1.16.5
Forge version: 36.2.0
Botania version: 1.16.5-419

### What I expected
The floral obedience stick inside the dispenser, when triggered, would rebind the flowers to the adjacent mana pool or mana spreader, maybe even with the same particle effects as using them by hand.
### What happened
The dispenser plays the dispenser sound effect when triggered and spawns the particles to indicate that the item has been used successfully, but flowers are not rebinded.
Dispensers with floral obedience sticks in them, in any orientation, facing a mana pool or mana spreader, binding floating flowers or planted flowers, generating or functional, does nothing besides pretend it triggered.

**Comment by Hubry** [comment] 2021-09-20 14:03
I think this is a duplicate of #3782 - this only *looks* like not working, but refresh the data by right clicking on the blocks with a wand and you will discover mana in different places than you expect.

Please try using [a build from Jenkins](https://ci.blamejared.com/job/Botania/job/master/) and let me know if it still occurs there.
(We are kinda overdue a release tbh...)

**Closed by Hubry** 2021-09-20 14:03 UTC
